# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Droplet deploy

on:
    push:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 19
                  cache: 'npm'
            - name: Build frontend
              working-directory: ./front
              run: |
                  npm ci
                  npm run build --if-present
            - name: Secure copy to the Droplet
              uses: cross-the-world/scp-pipeline@v1.2.1
              with:
                  host: ${{ secrets.SSH_HOST }}
                  user: ${{ secrets.SSH_USER }}
                  port: ${{ secrets.SSH_PORT }}
                  key: ${{ secrets.SSH_KEY }}
                  scp: |
                      ./front/build/* => /var/www/html/random/front
